parameters:
  - name: terraformVersion
    type: string

steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
    displayName: 'Use Terraform ${{ parameters.terraformVersion }}'
    inputs:
      terraformversion: ${{ parameters.terraformVersion }}