parameters:
  - name: azureSubscription
    type: string
  - name: resourceGroup
    type: string
  - name: statefileName
    type: string
  - name: environmentSuffix
    type: string
  - name: workingDirectory
    type: string

steps:
  - task: AzureCLI@2
    displayName: 'Create TF State Storage Account and Container'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      scriptType: pscore
      scriptLocation: inlineScript
      workingDirectory: ${{ parameters.workingDirectory }}
      addSpnToEnvironment: true
      inlineScript: |
        dir
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
    displayName: 'Terraform: Init'
    inputs:
      workingDirectory: ${{ parameters.workingDirectory }}
      backendServiceArm: ${{ parameters.azureSubscription }}
      backendAzureRmResourceGroupName: ${{ parameters.resourceGroup }}
      backendAzureRmStorageAccountName: 'tfmybookinglibrary${{parameters.environmentSuffix}}'
      backendAzureRmContainerName: 'state'
      backendAzureRmKey: ${{ parameters.statefileName }}
