parameters:
  - name: workingDirectory
    type: string
steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
    displayName: 'Terraform: Validate'
    inputs:
      command: validate
      workingDirectory: ${{ parameters.workingDirectory }}
