parameters:
  - name: workingDirectory
    type: string
steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
    displayName: 'Terraform: Validate'
    inputs:
      command: validate
      workingDirectory: ${{ parameters.workingDirectory }}
