parameters:
  - name: dotnetVersion
    type: string
  - name: terraformVersion
    type: string
  - name: stateFile
    type: string
  - name: tfParallelism
    type: number
  - name: environments
    type: object
    default: []

stages:
  - stage: build
    jobs:
      {% comment %} - template: '../jobs/functions.yml'
        parameters:
          dotnetVersion: ${{ parameters.dotnetVersion }}
          buildDirectory: 'fn-mybooklibrary/mbl-app.csproj'
          artifactName: 'function'

      - template: '../jobs/solution_test.yml'
        parameters:
          dotnetVersion: ${{ parameters.dotnetVersion }}
          buildDirectory: 'MyBookLibrary.sln'
          solution: 'MyBookLibrary'      

      - template: '../jobs/publish_infrastructure.yml' {% endcomment %}

      - ${{ each environment in parameters.environments }}:
          - template: '../jobs/infrastructure.yml'
            parameters:
              azureSubscription: '${{ environment }}'
              terraformVersion: ${{ parameters.terraformVersion }}
              tfParallelism: ${{ parameters.tfParallelism }}
              environment: ${{ environment }}
              stateFile: ${{ parameters.statefile }}

