parameters:
  - name: dotnetVersion
    type: string
  - name: terraformVersion
    type: string
  - name: stateFile
    type: string
  - name: tfParallelism
    type: number
  - name: environments
    type: object
    default: []

stages:
  - stage: build
    jobs:
      
      - ${{ each environment in parameters.environments }}:
          - template: '../jobs/infrastructure.yml'
            parameters:
              azureSubscription: '${{ environment }}'
              terraformVersion: ${{ parameters.terraformVersion }}
              tfParallelism: ${{ parameters.tfParallelism }}
              environment: ${{ environment }}
              stateFile: ${{ parameters.statefile }}

