parameters:
  - name: artifactName
    type: string

steps:
  - task: ArchiveFiles@2
    displayName: "Archive Files"
    inputs:
      archiveFile: "$(Build.ArtifactsStagingDirectory)/${{ parameters.artifactName }}.zip"
      archiveType: "zip"
      includeRootFolder: false
      rootFolderOrFile: "$(Build.ArtifactStagingDirectory)/${{ parameters.artifactName }}"
