parameters:
  - name: buildDirectory
    type: string

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet'

  - task: NuGetCommand@2
    displayName: 'Nuget Restore'
    condition: ne(variables.CACHE_RESTORED, true)
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Build Solution'
    inputs:
      command: build
      projects: ${{ parameters.buildDirectory }}
      zipAfterPublish: true

  - task: DotNetCoreCLI@2
    displayName: 'Execute Test'
    inputs:
      command: test
      projects: |
        **/Tests/*.csproj
      arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
      publishTestResults: true
